#pragma config(Motor,  port1,           rightTest1,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightTest2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightTest3,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightTest4,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftTest1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftTest2,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftTest3,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftTest4,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           rightButton,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftButton,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{
		//Test the first 8 ports using the remotes
		motor[rightTest1] = vexRT[Ch2];
    motor[rightTest2] = vexRT[Ch1];
    motor[rightTest3] = vexRT[Ch2Xmtr2];
    motor[rightTest4] = vexRT[Ch1Xmtr2];
    motor[leftTest1] = vexRT[Ch3];
    motor[leftTest2] = vexRT[Ch4];
    motor[leftTest3] = vexRT[Ch3Xmtr2];
    motor[leftTest4] = vexRT[Ch4Xmtr2];

    //Test second to last port using button
    if(vexRT[Btn6U] == 1)
    {
      motor[rightButton] = 127;
    }
    else if(vexRT[Btn6D] == 1)
    {
      motor[rightButton] = -127;
    }
    else
    {
      motor[rightButton] = 0;
    }

    //Test last port using button
    if(vexRT[Btn5U] == 1)
    {
      motor[leftButton] = 127;
    }
    else if(vexRT[Btn5D] == 1)
    {
      motor[leftButton] = -127;
    }
    else
    {
      motor[leftButton] = 0;
    }
  }
}
